### ISSUE TITLE
Dock disappears after unlocking the screen

### ISSUE THREAD

**Issue by dangvd** [dangvd/crystal-dock#98]
From EliteAMDGamer:

It happens in my case when either I manually shut off the monitor when I walk away from the system. Or when the display automatically shuts off after four hours of inactivity.

I don't use sleep or anything currently because they don't really function to well. But the dock will appear with autostart on boot or sddm login.

I have not tested it with plasma's lock screen, but I don't think it would open then either.

~Update-

So when using hibernate or suspend it works normally as expected i think cause the system comes on to the lock screen. If there was a way to have the dock spit out a log i would be happy to add that in.

Here's what i get from opening it in terminal. Shutting off the screen manually an truing it back on. So maybe its on QT.

crystal-dock
QSocketNotifier: Can only be used with threads started with QThread
Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash

---

From TheCrustyCurmudgeon:

I've installed crystal-dock-2.7-1.qt6.7.x86_64.rpm in Fedora 41 w/ Wayland (KDE Plasma Version: 6.2.2, KDE Frameworks Version: 6.7.0, Qt Version: 6.7.2, Kernel Version: 6.11.5-300).

It seems that Crystal Dock does not reappear after restoring from lock. I do not have sleep/hibernate enabled, so my system just locks when idle. My session setting is set to "Start with an empty Session". Crystal Dock is enabled in autostart and it does start on a reboot. Just not on restore from lock.

**Comment by dangvd** [comment]
I believe the relevant error message was:
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash

Also I believe this happens when the screen turned off.
It relates to screen lock because the default setting for turning off screen is like 1 hour normally and 1 minute if screen lock is on.
I've verified this on my Fedora 41: when I disabled turning off screen, it stopped happening.

**Comment by BigCrustyOne** [comment]
> I believe the relevant error message was: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
> 
> Also I believe this happens when the screen turned off. It relates to screen lock because the default setting for turning off screen is like 1 hour normally and 1 minute if screen lock is on. I've verified this on my Fedora 41: when I disabled turning off screen, it stopped happening.

Understood.  Unfortunate... screen turn-off is important to me and I would assume,  anyone who wants to reduce electricity use.  Not willing to abandon that practice, so I'll have to live with restarting crystal dock for now.

**Comment by BigCrustyOne** [comment]
> I believe the relevant error message was: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
> 
> Also I believe this happens when the screen turned off. It relates to screen lock because the default setting for turning off screen is like 1 hour normally and 1 minute if screen lock is on. I've verified this on my Fedora 41: when I disabled turning off screen, it stopped happening.

Just tested this on Fedora 41 after some updates this morning.  Locking the system w/ CTRL+L, then allowing the screen to turn off.  woke up screen and logged in to find Crystal Dock stiil running (happy dance!).  Will double-check that with a longer test, but seems to have been resolved by some update in the last 18 hours.

**Comment by dangvd** [comment]
Thanks for the update, I'll look more into it.

**Comment by coffeinflash** [comment]
Can confirm this issue using openSUSE Tumbleweed.

I am using the package build by my own on OBS: https://build.opensuse.org/package/show/home:Herbster0815/crystal-dock

Not sure if it is related but I had a similar issue with conky (conky disappered after signal loss on monitor due to standby) and this is fixed since Plasma 6.2.2, at least for me.

Actually a simple workaround would be monitoring the PID - if it is gone after wakeup, restart crystal-dock.

**Comment by rjwest000** [comment]
The dock is great, BUT I also have this issue on my desktop (AMD Ryzen 9, AMD graphics and HDMI monitor) but strangely not on my older HP Intel Core i5 laptop.

Both machines have a newly installed OS (Fedora Linux KDE 41), with default settings, plus the crystal-dock-2.7-1.x86_64.rpm package.

**Comment by ssteinerx** [comment]
I am also experiencing this whenever the screen shuts off on:
```plaintext
  Operating System: Kubuntu 24.10
  KDE Plasma Version: 6.1.5
  KDE Frameworks Version: 6.6.0
  Qt Version: 6.6.2
  Kernel Version: 6.11.0-9-generic (64-bit)
  Graphics Platform: Wayland
```
This is in syslog, maybe it'll be helpful. the "parent is not mapped" message shows up thousands of times.  5,240 to be exact.

```plaintext
2024-11-10T19:25:07.356390-05:00 B450M-DS3H crystal-dock[730404]: [Parent 730404, Main Thread] WARNING: Couldn't map window 0x7e54ef94e2c0 as subsurface because its parent is not mapped.: 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:187
2024-11-10T19:37:12.634148-05:00 B450M-DS3H systemd[3368]: Started app-crystal\x2ddock@cff9cd20eee1480b91b7af4af4b69e08.service - Crystal Dock - Desktop Panel.
2024-11-10T19:37:12.659956-05:00 B450M-DS3H crystal-dock[916659]: QSocketNotifier: Can only be used with threads started with QThread
2024-11-10T19:37:13.116610-05:00 B450M-DS3H crystal-dock[916659]: Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
2024-11-10T19:37:13.121435-05:00 B450M-DS3H crystal-dock[916659]: Could not find icon with name:  in the current icon theme and its fallbacks. The window icon will have limited functionalities.
```

**Comment by ssteinerx** [comment]
Again, I'm not sure how helpful this might be, but here is a collection of the *unique*-ish messages from syslog.  Since this is on Plasma 6.x and Qt 6.6.x, (first time *I've* been running either of those on an actual machine), I thought this might be kind of generally useful.

It's not perfectly "deduped" but I have a regex headache so it's going to have to do...

[syslog-unique-11.txt](https://github.com/user-attachments/files/17694268/syslog-unique-11.txt)

**Comment by dangvd** [comment]
Thanks for all the additional info, I will update the bug as soon as I've found a fix.

**Comment by ssteinerx** [comment]
Just for the record...

I am having krunner quit responding unexpectedly and even the whole plasma desktop go into outer space for no apparent reason.  

While there may be something specific about Crystal Dock quitting when the display blanks, Crystal Dock is not the only thing going kaflooie while the system has the display off.  Whether the "display off" part has *anything to do with it* is unknown but, if you think about it, if the display is off, you haven't generated any UI-ish events for a while so it may have doodly to to do with the display turning off at all. 

All I know is that Crystal Dock quits 50 times a day, krunner stops responding about 15, and about once or twice a day the whole plasma universe just goes out the window (so to speak).  Welcome to KDE, Plasma, and QT _all new-ish_ versions 6.x.x.  

**Now with Wayland where you never know which "way" things be goin' but they seem to be going "*a*-way".**

**Comment by dangvd** [comment]
Yeah this bug is very annoying, and it seems it's because of something underneath. I tried running with gdb but it just said the dock exited normally (when the screen turned off), and I did not get any stack trace / dump so it's hard to debug...

**Comment by ssteinerx** [comment]
> I did not get any stack trace / dump so it's hard to debug...

And if *that's* not annoying then I guess I don't know what is.

`Are` you catching a signal at that point that seems to be telling you to shut down?  That would make some sense; especially if they mucked with the specific meanings of signals between QT/Plasma versions.  Like "Quit updating the display" mutated to "Quit...".  Wouldn't be the first time a "subtle" change in the underlying system led to sub-optimal results.

Let me see if I can make a debug build and give it a whirl under the "6 eyes are better than 2" theory.

**Comment by dangvd** [comment]
I asked about this on KWin mailing list and was advised to file a bug on Qt bug tracker so I created one here:
https://bugreports.qt.io/browse/QTBUG-131387

Hopefully we'll get something out of it.

**Comment by ssteinerx** [comment]
Unfortunately, they seem to want you to tell them what the bug is so they can help you find the bug.  Oh boy.

**Comment by dangvd** [comment]
Well I've created a minimal code example to illustrate this bug and posted it both on Qt and KDE layer-shell-qt bug tracker.

Let's see how the responses are.

In case someone interested this is the minimal code:

```
#include <QApplication>
#include <QWidget>
#include <QWindow>

#include <LayerShellQt/Window>

int main(int argc, char** argv) {
  QApplication app(argc, argv);

  QWidget dock;
  dock.winId();  // we need this for widget->windowHandle() to not return nullptr.
  auto* layerShellWin = LayerShellQt::Window::get(dock.windowHandle());

  // Same bug if for example this is called instead:
  // layerShellWin->setAnchors(LayerShellQt::Window::AnchorBottom);
  layerShellWin->setLayer(LayerShellQt::Window::LayerBottom);

  dock.show();

  return app.exec();
}

```

**Comment by coffeinflash** [comment]
Just for the record here is my current workaround:

#! /bin/bash
APP="crystal-dock"

while true; do
        if [ ! $(pidof $APP) ]; then
                crystal-dock
        fi
        sleep 5
done

I have added this to plasma autostart and it seems to work, when I switch from DP (Windows-VM)  to HDMI (Tumbleweed) on my monitor.

**Comment by dangvd** [comment]
@coffeinflash Thanks, yeah that would work as a temporary work-around.

**Comment by ssteinerx** [comment]
This is a summary; I'm not familiar enough with the code, nor do I have time to become so...this just bugs me.

I've not attempted to figure out what code is still using `xwaylandvideobridge`, or what is going on with `org.kde.plasmashell` specifically, but my suspicion is that whatever error handling is being used when those things fail is leaving something in a default-to-just-quitting state and, since it's the default, it's not an error.

Starting with enabling WAYLAND_DEBUG:

```shell
$ WAYLAND_DEBUG=1 crystal-dock &
[1] 202931
ssteiner@B450M-DS3H:~
$ QSocketNotifier: Can only be used with threads started with QThread
Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
Could not find application with id: org.kde.plasmashell. The window icon will have limited functionalities.
```
A bit of digging and:

KDE Plasma 6

> Changes concerning the `org.kde.xwaylandvideobridge` and `org.kde.plasmashell` services:

1. `org.kde.xwaylandvideobridge`

    `xwaylandvideobridge` was introduced to <blah, blah, blah>... **this service is no longer necessary and has been phased out in Plasma 6.**
    
    [KDE Discuss](https://discuss.kde.org/t/plasma-6-xwayland-video-bridge-broken/11048)

    **_Update Dependencies: Ensure your application does not rely on deprecated services like `xwaylandvideobridge`._**

2. `org.kde.plasmashell`

    Status: The `plasmashell` service remains integral to KDE Plasma's functionality <blah, blah, blah>...

    Details: While plasmashell continues to be a core component, there have been **updates and improvements** (read: new bugs)... Plasma 6 migration guides...

    [Debian Wiki](https://wiki.debian.org/Plasma%206)

**Comment by dangvd** [comment]
@ssteinerx Thanks for the post but it is not relevant to the bug.
As noted in https://github.com/dangvd/crystal-dock/issues/98#issuecomment-2513079037:
this bug was caused by LayerShellQt / Qt and could be reproduced with a minimal code like that.

Again bugs have been filed in those libraries:
https://bugreports.qt.io/browse/QTBUG-131387
https://bugs.kde.org/show_bug.cgi?id=496963

Let's wait for fixes from those libraries.

**Comment by coffeinflash** [comment]
Just kidding, but you could integrate my little workaround. It works great since weeks, so actually I do not notify this bug anymore.

**Comment by ssteinerx** [comment]
> @ssteinerx Thanks for the post but it is not relevant to the bug. As noted in [#98 (comment)](https://github.com/dangvd/crystal-dock/issues/98#issuecomment-2513079037): this bug was caused by LayerShellQt / Qt and could be reproduced with a minimal code like that.
> 
> Again bugs have been filed in those libraries: https://bugreports.qt.io/browse/QTBUG-131387 https://bugs.kde.org/show_bug.cgi?id=496963
> 
> Let's wait for fixes from those libraries.

That's what prompted this grasping at straws -- they seem kind of stalled.  

On the QT bug, a day after you submitted the minimal app:

> Petri Virkkunen](https://bugreports.qt.io/secure/ViewProfile.jspa?name=pevirkku) made changes - 03 Dec '24 09:52
> Priority 	Original: Not Evaluated [ 6 ] 	New: P2: Important [ 3 ]

Nothing at all on the kde one.

Maybe I'm a just jumpy from watching bugs just disappear into the black holes at [Apple, Microsoft, et al.].

**Comment by dangvd** [comment]
@ssteinerx I understand but if you post irrelevant debug info here, it will make it harder to follow so please use the minimal code in https://github.com/dangvd/crystal-dock/issues/98#issuecomment-2513079037 to debug. Thanks.

**Comment by dangvd** [comment]
I believe this has been fixed on recent versions of Qt. On both Fedora and Kubuntu, I don't see this issue anymore.

**Comment by ssteinerx** [comment]
Sorry to say, this is still happening with 2.16.

```text
Operating System: Kubuntu 25.10
KDE Plasma Version: 6.4.5
KDE Frameworks Version: 6.17.0
Qt Version: 6.9.2
Kernel Version: 6.17.0-14-generic (64-bit)
Graphics Platform: Wayland
```

**Comment by dangvd** [comment]
Yeah still happening.

**Comment by 1UPNuke** [comment]
I decided to use a systemd user service as a band-aid solution, maybe it'll be useful to someone else as well:
```ini
[Unit]
Description=Crystal Dock Restart Service
PartOf=graphical-session.target
After=graphical-session.target
Requisite=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
ExecStart=/usr/bin/env crystal-dock
Restart=always
# Prevents launched programs from closing with the dock
KillMode=process

[Install]
WantedBy=graphical-session.target
```

**Comment by hermitguo** [comment]
ENV: Ubuntu budgie 26.04 wayland (labwc) + fctix5

<img width="836" height="476" alt="Image" src="https://github.com/user-attachments/assets/c3483962-21c0-444c-860f-1974086b5d33" />

```
ubuntu@master:/var/crash$ apport-unpack /var/crash/_usr_lib_x86_64-linux-gnu_budgie-desktop_raven-plugins_org.ubuntubudgie.raven.widget.budgie-showtime_showtime-desktop.1000.crash /tmp/wpx-crash && cat /tmp/wpx-crash/Stacktrace 2>/dev/null
#0  0x00007c547d15d301 in g_type_check_instance_is_fundamentally_a () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007c547d1422c7 in g_object_ref () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x000063f883c67249 in ??? ()
#3  0x000063f883c673ad in ??? ()
#4  0x00007c547d13568c in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007c547d153bc9 in ??? () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007c547d155b66 in ??? () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007c547d156095 in g_signal_emit_by_name () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007c547d277250 in ??? () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007c547b932056 in ??? () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#10 0x00007c547b92dd16 in ??? () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#11 0x00007c547b9307ae in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#12 0x00007c547bc5598b in ??? () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#13 0x00007c547bc567c9 in ??? () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#14 0x00007c547bc56bc3 in wl_display_dispatch_queue_pending () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#15 0x00007c547d268150 in ??? () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007c547d232f1b in gdk_display_get_event () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#17 0x00007c547d27079e in ??? () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#18 0x00007c547c5dcb9b in ??? () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007c547c5de1d7 in ??? () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007c547c5de577 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007c547cc0fc05 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x000063f883c65901 in ??? ()
#23 0x00007c547c02a601 in __libc_start_call_main (main=main@entry=0x63f883c64f90, argc=argc@entry=2, argv=argv@entry=0x7ffdae83d5c8) at ../sysdeps/nptl/libc_start_call_main.h:59
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -646257657922250200, 140727531328968, 2, 136702319796224, 109919013877848, -646257657926444504, -1127116965622506968}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x7ffdae83d5c8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#24 0x00007c547c02a718 in __libc_start_main_impl (main=0x63f883c64f90, argc=2, argv=0x7ffdae83d5c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdae83d5b8) at ../csu/libc-start.c:360
#25 0x000063f883c66265 in ??? ()ubuntu@master:/var/crash$ 
ubuntu@master:/var/crash$ 
```

Analysis of the root cause of the crash: The stack information provides key clues:

- Crash entry: g_type_check_instance_is_fundamentally_a → g_object_ref – A wild pointer or a destroyed GObject object is forcibly referenced.
- At the call chain level: Wayland client event distribution → GDK3 Wayland backend → GTK3 window signal triggering → Budgie ShowTime clock plugin
- Trigger condition: Labwc (Wayland) turns off the display power (DPMS sleep mode)
- Phenomenon chain: Budgie-panel and Crystal-Dock both crashed simultaneously, involving GTK3 Wayland client components.

Core Bug Cause: When Labwc sends a DPMS display offline event:

- GDK Wayland destroys the corresponding display/surface GDK object
- The signal callback functions of the Budgie ShowTime plugin, CrystalDock, and Budgie Panel do not perform object existence validation.
- When a dormant event triggers a callback, the control object has already been released; however, g_object_ref is still executed, directly causing an GObject assertion crash.
- The Ubuntu 26.04 Budgie + Labwc combination features: a native Budgie window manager that supports the DPMS object lifecycle, and a Labwc compatibility layer lacking synchronization and destruction mechanisms.
